# Generated by Django 4.2.16 on 2024-11-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor", "0003_alter_vendor_vendor_slug"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="vendors",
            field=models.ManyToManyField(blank=True, to="vendor.vendor"),
        ),
    ]
